version: '3.1'

services:

  unit-certificate:
    image: golang:latest
    volumes:
      - ./services/certificate:/usr/src/certificate
      - /tmp/go:/go
    working_dir: /usr/src/certificate
    command: bash -c "pwd && go mod download && go test --cover -v ./..."